# Part 1
### Section 2.5 states that real networks are sparse. Can you think of a real network where each node has many connections? Is that network still sparse? If yes, can you explain why?

A school teacher network, representing connections between teachers based on shared classes or subjects, might seem dense at first glance because teachers have multiple connections (for instance, to different students or other teachers). However, in reality, such a network is still likely to be sparse. This is because each teacher is not connected to every other teacher in the network — rather, they are only connected to those who share subjects or students. The total number of possible connections in the school is large, and even with many connections, the network remains sparse because the actual number of connections between teachers is small compared to the potential number of connections.

# Part 2
## Homework section 2.12
### Königsberg Problem 

#### The vector k whose elements are the degrees ki of all nodes i = 1, 2,..., N.


In [34]:
import numpy as np

# NxN adjacency matrix A for figure a. The vector k whose elements are the degrees k_i of all nodes i = 1, 2,..., N.
A = np.array([[0, 1, 0, 1],
              [1, 0, 1, 1],
              [0, 1, 0, 1],
              [1, 1, 1, 0]])


# V1 is a vector of ones where the number of rows is equal to the number of rows in A
V1 = np.ones((A.shape[0], 1))

# k is the degree of each node 
k = np.dot(A, V1)
print(k)


[[2.]
 [3.]
 [2.]
 [3.]]


#### The total number of links, L, in the network:
The total amount of link is L = 1/2 * sum(all entries of A) so;

Sum of entries of A = 2 + 3 + 2 + 3 = 10

L = 1/2 * 10 = 5

#### The number of triangles T present in the network, where a triangle means three nodes, each connected by links to the other two:

Given the adjacency matrix 𝐴 which tells us whether there is an edge between two nodes (1 if connected, 0 if not),  $𝐴^3$ is the matrix you get when you multiply the adjacency matrix by itself three times. 
Each element represents the number of different ways you can travel from node i to node j by following exactly three edges (a walk of length 3). A triangle is a closed loop involving three nodes. If a set of three nodes forms a triangle, then you can start at any of those nodes, visit the other two, and return to your starting point in exactly three steps. When you compute the cube of the adjacency matrix $A^3$, the diagonal elements tell us how many ways you can make a closed walk of length 3 starting and ending at node 𝑖. For a triangle, this means that each diagonal element counts how many triangles the node is part of. The trace of a matrix Tr($𝐴^3$) is the sum of all the diagonal elements of $A^3$. Since we count each triangle six times (once for each possible way of walking around the triangle), we need to divide by 6 to avoid overcounting. This gives the correct number of distinct triangles in the network.

In [35]:
# Compute A^3
A_cubed = np.linalg.matrix_power(A, 3)

# Compute the trace of A^3
trace_A_cubed = np.trace(A_cubed)

# Compute the number of triangles
T = trace_A_cubed / 6
print(T)

2.0


#### The vector $k_{nn}$ whose element i is the sum of the degrees of node i's neighbors:

Now we want to calculate the sum of the degrees of the neighbors for each node. To calculate $k_{nn} = Ak$, we multiply the adjacency matrix 𝐴 by the degree vector k. This gives us:

In [36]:
knn = np.dot(A, k)
print(knn)

[[6.]
 [7.]
 [6.]
 [7.]]


#### Interpretation of the Result:
- Node 1: The sum of the degrees of its neighbors is 6.
- Node 2: The sum of the degrees of its neighbors is 7.
- Node 3: The sum of the degrees of its neighbors is 6.
- Node 4: The sum of the degrees of its neighbors is 7.

This vector tells us the total number of connections that the neighbors of each node have.

#### The vector $k_{nnn}$ whose element i is the sum of the degrees of node i's second neighbors:
To find the second neighbors, we multiply the adjacency matrix by itself. $A^2$ contains the number of paths of length 2 between any two nodes. Each non-zero entry indicates that nodes are connected through a common neighbor.

##### Sum of degrees of second neighbors:

To calculate the sum of the degrees of node i's second neighbors, we multiply $A^2$ by the degree vector k:

$$k_{nnn}=A^2k$$

In [37]:
A_squared = np.linalg.matrix_power(A, 2)
knnn = np.dot(A_squared, k)
print(knnn)

[[14.]
 [19.]
 [14.]
 [19.]]


### Graph representation

In [38]:
import numpy as np
import matplotlib.pyplot as plt

G = nx.Graph()
G.add_nodes_from(range(1, 7))
G.add_edges_from([(1, 2), (1, 3), (1, 4), (1, 6)])  
G.add_edges_from([(2, 3), (2, 4), (3, 6)])  
adj_matrix_G = nx.adjacency_matrix(G).todense()
print("Adjacency matrix for G:")
print(np.array(adj_matrix_G))
# Print adjacency list of each node
for node, neighbors in G.adjacency():
    print(f"Node {node} has neighbors {list(neighbors)}")
avg_clustering_coefficient = nx.average_clustering(G)

print(f"Average clustering coefficient: {avg_clustering_coefficient}")

print('\n')
DG = nx.DiGraph()
DG.add_nodes_from(range(1, 7))
DG.add_edges_from([(1, 2), (2, 3), (3, 2), (2, 4),(3, 1),(4, 1), (6, 3), (6, 1)])
adj_matrix_DG = nx.adjacency_matrix(DG).todense()
print("Adjacency matrix for DG:")
print(np.array(adj_matrix_DG))
# Print adjacency list of each node
for node, neighbors in DG.adjacency():
    print(f"Node {node} has neighbors {list(neighbors)}")

#nx.draw(G, with_labels=True, node_color='lightblue', node_size=700, font_size=12, font_color='black')
#plt.show()


Adjacency matrix for G:
[[0 1 1 1 0 1]
 [1 0 1 1 0 0]
 [1 1 0 0 0 1]
 [1 1 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 1 0 0 0]]
Node 1 has neighbors [2, 3, 4, 6]
Node 2 has neighbors [1, 3, 4]
Node 3 has neighbors [1, 2, 6]
Node 4 has neighbors [1, 2]
Node 5 has neighbors []
Node 6 has neighbors [1, 3]
Average clustering coefficient: 0.6388888888888888


Adjacency matrix for DG:
[[0 1 0 0 0 0]
 [0 0 1 1 0 0]
 [1 1 0 0 0 0]
 [1 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 1 0 0 0]]
Node 1 has neighbors [2]
Node 2 has neighbors [3, 4]
Node 3 has neighbors [2, 1]
Node 4 has neighbors [1]
Node 5 has neighbors []
Node 6 has neighbors [3, 1]


## Information You Can Infer from Both:

1. Connections/Edges: Both representations can tell you whether two nodes are directly connected (i.e., if there is an edge between them).
2. Degree of a Node: Both the adjacency list and adjacency matrix allow you to calculate the degree of a node, which is the number of connections a node has.

## Information You Cannot Easily Infer from the Adjacency List but Can from the Adjacency Matrix:
1. Global Structure Information:

    - Transitivity and Higher-Order Connectivity: In the adjacency matrix, relationships between neighbors (such as common neighbors) are much easier to infer because matrix multiplication allows you to count paths of any length between nodes. In the adjacency list, this is harder to infer since you'd need to manually traverse neighbors.

    - Triangle Counting and Clustering: The adjacency matrix makes it easier to find triangles (groups of three mutually connected nodes) and calculate the clustering coefficient by multiplying matrices. In the adjacency list, you'd have to explicitly check if the neighbors of one node are connected to each other, which is computationally more complex.

2. Symmetry and Edge Weights:

    - Symmetry in Undirected Graphs: In the adjacency matrix, an undirected graph will always have a symmetric matrix, which is immediately apparent. In the adjacency list, you would need to check each neighbor list manually to confirm this.
    
    - Edge Weights: In weighted graphs, the adjacency matrix can store the weight of each edge as a value in the matrix, making it easy to look up edge weights. In an adjacency list, you would need to modify the list   structure to store the weights with each connection.

3. Efficient Queries for Edge Existence:

    - Constant-Time Edge Lookup: In an adjacency matrix, you can immediately check if an edge exists between any two nodes by looking up the corresponding matrix entry in constant time O(1). In an adjacency list, you would need to search through the list of neighbors, which takes linear time O(k) (where k is the degree of the node).

4. Space Complexity and Sparsity:

    - Density and Sparsity: The adjacency matrix makes it easier to see if the graph is dense or sparse. For example, if most matrix entries are 0, you can tell the graph is sparse. In the adjacency list, you cannot directly infer this global property from just examining the lists.

5. Spectral Properties of the Graph:

    - Eigenvalues and Eigenvectors: The adjacency matrix allows for easy computation of the graph's eigenvalues and eigenvectors, which are important in spectral graph theory. These can provide information about the graph’s structure, such as connectivity and community detection. These kinds of operations are not easily performed with an adjacency list.

## In the (a) network, how many paths (with possible repetition of nodes and links) of length 3 exist starting from node 1 and ending at node 3? And (b).

1. Compute $A^3$
2. Read value at (1,3), so row 1, column 3 is the number of paths. 

In [42]:
A_3 = np.linalg.matrix_power(adj_matrix_G, 3)

# Find the number of paths from node 1 to node 3 (REMEMBER indexing starts at 0)
num_paths_length_3 = A_3[0, 2]

print(f"Number of paths of length 3 from node 1 to node 3 for graph a: {num_paths_length_3}")

A_3 = np.linalg.matrix_power(adj_matrix_DG, 3)

num_paths_length_3 = A_3[0, 2]
print(f"Number of paths of length 3 from node 1 to node 3 for graph b: {num_paths_length_3}")


Number of paths of length 3 from node 1 to node 3 for graph a: 7
Number of paths of length 3 from node 1 to node 3 for graph b: 0
